/**
 * Games data for Monster Survivors
 * Contains game information and links
 */

const gamesData = [
    {
        id: "train-miner",
        name: "Train Miner",
        description: "Control your train and collect minerals along the tracks. Upgrade your train and earn points in this addictive mining game.",
        shortDescription: "Mine resources with your train in this exciting adventure!",
        category: "adventure",
        controls: "Mouse/Touch to control",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TrainMinerTeaser.jpg",
        gameUrl: "https://play.famobi.com/train-miner",
        featured: true,
        popular: false
    },
    {
        id: "rise-up",
        name: "Rise Up",
        description: "Guide your balloon to rise as high as possible while protecting it from obstacles. Test your reflexes and timing in this challenging skill game.",
        shortDescription: "Help your balloon rise and avoid obstacles!",
        category: "skill",
        controls: "Mouse/Touch to move shield",
        rating: 4.7,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RiseUpTeaser.jpg",
        gameUrl: "https://play.famobi.com/rise-up",
        featured: true,
        popular: false
    },
    {
        id: "giant-rush",
        name: "Giant Rush",
        description: "Run, grow, and crush everything in your path! Collect power-ups to grow bigger and smash through obstacles in this action-packed game.",
        shortDescription: "Grow into a giant and smash through obstacles!",
        category: "action",
        controls: "Swipe/Arrow keys to move",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GiantRushTeaser.jpg",
        gameUrl: "https://play.famobi.com/giant-rush",
        featured: true,
        popular: false
    },
    {
        id: "western-sniper",
        name: "Western Sniper",
        description: "Test your aim and reflexes in this wild west shooting game. Take down targets with precision and become the best sharpshooter in the west.",
        shortDescription: "Become the best sharpshooter in the Wild West!",
        category: "action",
        controls: "Mouse to aim and shoot",
        rating: 4.8,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/WesternSniperTeaser.jpg",
        gameUrl: "https://play.famobi.com/western-sniper",
        featured: true,
        popular: false
    },
    {
        id: "go-escape",
        name: "Go Escape",
        description: "Navigate through challenging mazes and find the exit. Use strategy and planning to solve each puzzle and progress through increasingly difficult levels.",
        shortDescription: "Find your way through challenging mazes!",
        category: "puzzle",
        controls: "Arrow keys/Swipe to move",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GoEscapeTeaser.jpg",
        gameUrl: "https://play.famobi.com/go-escape",
        featured: false,
        popular: true
    },
    {
        id: "color-fill-3d",
        name: "Color Fill 3D",
        description: "Fill the board with color while avoiding obstacles. Plan your moves carefully to complete each level in this relaxing yet challenging puzzle game.",
        shortDescription: "Fill the board with colors in this 3D puzzle!",
        category: "puzzle",
        controls: "Mouse/Touch to draw",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorFill3dTeaser.jpg",
        gameUrl: "https://play.famobi.com/color-fill-3d",
        featured: false,
        popular: true
    },
    {
        id: "spot-the-cat",
        name: "Spot The Cat",
        description: "Find the hidden cats in each level. Train your observation skills with this fun and challenging puzzle game for all ages.",
        shortDescription: "Can you find all the hidden cats?",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.2,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpotTheCatTeaser.jpg",
        gameUrl: "https://play.famobi.com/spot-the-cat",
        featured: false,
        popular: true
    },
    {
        id: "color-roll-3d",
        name: "Color Roll 3D",
        description: "Roll your ball and match colors to progress. Navigate through challenging tracks and avoid obstacles in this addictive 3D rolling game.",
        shortDescription: "Roll, match colors, and reach the finish line!",
        category: "skill",
        controls: "Swipe/Arrow keys to move",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorRoll3dTeaser.jpg",
        gameUrl: "https://play.famobi.com/color-roll-3d",
        featured: false,
        popular: true
    },
    {
        id: "color-water-sort-3d",
        name: "Color Water Sort 3D",
        description: "Sort the colored water by pouring it between bottles. Use logic and planning to solve each puzzle and complete all the levels.",
        shortDescription: "Sort colored water between bottles in this brain teaser!",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorWaterSort3dTeaser.jpg",
        gameUrl: "https://play.famobi.com/color-water-sort-3d",
        featured: false,
        popular: false
    },
    {
        id: "braindom",
        name: "Braindom",
        description: "Test your intelligence with tricky brain teasers. Think outside the box to solve each unique puzzle and challenge your mind.",
        shortDescription: "Solve tricky brain teasers that challenge your thinking!",
        category: "puzzle",
        controls: "Mouse/Touch to interact",
        rating: 4.7,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BraindomTeaser.jpg",
        gameUrl: "https://play.famobi.com/braindom",
        featured: false,
        popular: false
    },
    {
        id: "sort-it",
        name: "Sort It",
        description: "Sort the colored balls into their matching tubes. Plan your moves carefully in this addictive and challenging puzzle game.",
        shortDescription: "Sort balls into matching tubes in this relaxing puzzle!",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SortItTeaser.jpg",
        gameUrl: "https://play.famobi.com/sort-it",
        featured: false,
        popular: false
    },
    {
        id: "cube-match",
        name: "Cube Match",
        description: "Match cubes of the same color to clear the board. Plan your moves carefully to solve each puzzle and progress through increasingly difficult levels.",
        shortDescription: "Match colors and solve challenging cube puzzles!",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CubeMatchTeaser.jpg",
        gameUrl: "https://play.famobi.com/cube-match",
        featured: false,
        popular: false
    },
    {
        id: "parking-jam",
        name: "Parking Jam",
        description: "Unblock the red car by moving other vehicles out of the way. Use logic and planning to solve each puzzle in this addictive parking game.",
        shortDescription: "Solve parking puzzles by moving cars around!",
        category: "puzzle",
        controls: "Mouse/Touch to drag",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ParkingJamTeaser.jpg",
        gameUrl: "https://play.famobi.com/parking-jam",
        featured: false,
        popular: false
    },
    {
        id: "fashion-battle",
        name: "Fashion Battle",
        description: "Compete in fashion contests to become the top stylist. Choose the best outfits and accessories to win over the judges and progress through your fashion career.",
        shortDescription: "Create stylish outfits and win fashion contests!",
        category: "skill",
        controls: "Mouse/Touch to select",
        rating: 4.2,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FashionBattleTeaser.jpg",
        gameUrl: "https://play.famobi.com/fashion-battle",
        featured: false,
        popular: false
    },
    {
        id: "fruit-party",
        name: "Fruit Party",
        description: "Match fruits to create delicious combinations. Collect power-ups and complete challenges in this tasty match-3 puzzle game.",
        shortDescription: "Match fruits and create yummy combinations!",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FruitPartyTeaser.jpg",
        gameUrl: "https://play.famobi.com/fruit-party",
        featured: false,
        popular: false
    },
    {
        id: "thief-puzzle",
        name: "Thief Puzzle",
        description: "Help the thief navigate through security systems to steal valuable treasures. Solve puzzles and avoid guards in this strategic adventure game.",
        shortDescription: "Solve puzzles to help the thief steal treasures!",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ThiefPuzzleTeaser.jpg",
        gameUrl: "https://play.famobi.com/thief-puzzle",
        featured: false,
        popular: false
    },
    {
        id: "guess-their-answer",
        name: "Guess Their Answer",
        description: "Test your knowledge of human behavior by guessing how most people would respond to various questions. Learn interesting facts about human psychology.",
        shortDescription: "Can you predict how most people would answer?",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GuessTheirAnswerTeaser.jpg",
        gameUrl: "https://play.famobi.com/guess-their-answer",
        featured: false,
        popular: false
    },
    {
        id: "neon-rider",
        name: "Neon Rider",
        description: "Race through neon-lit tracks in this fast-paced arcade game. Avoid obstacles, collect power-ups, and reach the finish line as quickly as possible.",
        shortDescription: "Race through neon tracks in this arcade challenge!",
        category: "action",
        controls: "Arrow keys/Swipe to move",
        rating: 4.7,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/NeonRiderTeaser.jpg",
        gameUrl: "https://play.famobi.com/neon-rider",
        featured: false,
        popular: false
    },
    {
        id: "speed-master",
        name: "Speed Master",
        description: "Test your reaction time and precision in this fast-paced skill game. Complete challenges and beat your own records to become the ultimate Speed Master.",
        shortDescription: "Test your reflexes in this fast-paced challenge!",
        category: "skill",
        controls: "Mouse/Touch to select",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SpeedMasterTeaser.jpg",
        gameUrl: "https://play.famobi.com/speed-master",
        featured: false,
        popular: false
    },
    {
        id: "alien-attack",
        name: "Alien Attack",
        description: "Defend Earth from invading aliens in this classic arcade shooter. Upgrade your weapons and defeat increasingly difficult waves of enemies.",
        shortDescription: "Save Earth from invading aliens in this action game!",
        category: "action",
        controls: "Mouse/Touch to shoot",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/AlienAttackTeaser.jpg",
        gameUrl: "https://play.famobi.com/alien-attack",
        featured: false,
        popular: false
    },
    {
        id: "peet-sneak",
        name: "Peet Sneak",
        description: "Help Peet sneak through challenging levels, avoiding guards and collecting treasures. Use stealth and quick reflexes to succeed in this exciting adventure.",
        shortDescription: "Sneak through levels and avoid detection!",
        category: "adventure",
        controls: "Tap/Click to move",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PeetSneakTeaser.jpg",
        gameUrl: "https://play.famobi.com/peet-sneak",
        featured: false,
        popular: false
    },
    {
        id: "cut-the-rope",
        name: "Cut the Rope",
        description: "Feed candy to Om Nom by cutting ropes strategically. Use physics and timing to solve increasingly challenging puzzles in this classic physics-based game.",
        shortDescription: "Cut ropes to feed candy to the adorable Om Nom!",
        category: "puzzle",
        controls: "Swipe/Click to cut ropes",
        rating: 4.8,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CutTheRopeTeaser.jpg",
        gameUrl: "https://play.famobi.com/cut-the-rope",
        featured: true,
        popular: true
    },
    {
        id: "toilet-run",
        name: "Toilet Run",
        description: "Help your character find a toilet in increasingly hilarious and challenging situations. Overcome obstacles and reach the toilet before it's too late!",
        shortDescription: "Race against time to find a toilet!",
        category: "action",
        controls: "Tap/Click to move",
        rating: 4.1,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ToiletRunTeaser.jpg",
        gameUrl: "https://play.famobi.com/toilet-run",
        featured: false,
        popular: false
    },
    {
        id: "block-painter",
        name: "Block Painter",
        description: "Paint your way through each level by filling blocks with color. Plan your route carefully to cover all blocks without getting stuck in this brain-teasing puzzle.",
        shortDescription: "Fill all blocks with color in this challenging puzzle!",
        category: "puzzle",
        controls: "Mouse/Touch to draw",
        rating: 4.2,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BlockPainterTeaser.jpg",
        gameUrl: "https://play.famobi.com/block-painter",
        featured: false,
        popular: false
    },
    {
        id: "pair-up-3d",
        name: "Pair Up 3D",
        description: "Match pairs of identical objects in this 3D memory game. Test your memory and concentration skills as you progress through increasingly challenging levels.",
        shortDescription: "Find matching pairs in this 3D memory challenge!",
        category: "puzzle",
        controls: "Mouse/Touch to select",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PairUp3dTeaser.jpg",
        gameUrl: "https://play.famobi.com/pair-up-3d",
        featured: false,
        popular: false
    },
    {
        id: "cowboy-swing",
        name: "Cowboy Swing",
        description: "Swing your way through the Wild West, collecting coins and avoiding obstacles. Test your timing and reflexes in this addictive casual game.",
        shortDescription: "Swing through the Wild West and collect coins!",
        category: "skill",
        controls: "Tap/Click to swing",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/CowboySwingTeaser.jpg",
        gameUrl: "https://play.famobi.com/cowboy-swing",
        featured: false,
        popular: false
    },
    {
        id: "go-around",
        name: "Go Around",
        description: "Navigate your ball around a circular track, avoiding obstacles and collecting power-ups. Test your reflexes and timing in this challenging arcade game.",
        shortDescription: "Navigate around a circular track and avoid obstacles!",
        category: "skill",
        controls: "Mouse/Touch to move",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GoAroundTeaser.jpg",
        gameUrl: "https://play.famobi.com/go-around",
        featured: false,
        popular: false
    },
    {
        id: "green-ball",
        name: "Green Ball",
        description: "Guide your green ball through increasingly complex levels filled with obstacles and puzzles. Use physics and timing to reach the goal in this challenging adventure.",
        shortDescription: "Roll through challenging levels with your green ball!",
        category: "adventure",
        controls: "Arrow keys/Swipe to move",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GreenBallTeaser.jpg",
        gameUrl: "https://play.famobi.com/green-ball",
        featured: false,
        popular: false
    },
    {
        id: "twisty-lines",
        name: "Twisty Lines",
        description: "Connect colored dots with twisting lines without crossing paths. Test your planning and spatial reasoning in this addictive puzzle game.",
        shortDescription: "Connect dots with twisting lines in this brain teaser!",
        category: "puzzle",
        controls: "Mouse/Touch to draw",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TwistyLinesTeaser.jpg",
        gameUrl: "https://play.famobi.com/twisty-lines",
        featured: false,
        popular: false
    },
    {
        id: "lawn-mower",
        name: "Lawn Mower",
        description: "Mow the entire lawn without running out of fuel. Plan your route carefully to cover all grass in this satisfying puzzle game.",
        shortDescription: "Mow all the grass in this relaxing puzzle game!",
        category: "puzzle",
        controls: "Mouse/Touch to move",
        rating: 4.2,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/LawnMowerTeaser.jpg",
        gameUrl: "https://play.famobi.com/lawn-mower",
        featured: false,
        popular: false
    },
    {
        id: "rising-squares",
        name: "Rising Squares",
        description: "Stack squares to reach new heights, but be careful not to drop any squares off the side. Test your precision and planning in this challenging skill game.",
        shortDescription: "Stack squares carefully to reach new heights!",
        category: "skill",
        controls: "Mouse/Touch to place",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/RisingSquaresTeaser.jpg",
        gameUrl: "https://play.famobi.com/rising-squares",
        featured: false,
        popular: false
    },
    {
        id: "tower-fall",
        name: "Tower Fall",
        description: "Guide your character to the bottom of the tower, jumping from platform to platform. Test your timing and reflexes in this exciting arcade game.",
        shortDescription: "Jump down the tower without falling!",
        category: "skill",
        controls: "Tap/Click to jump",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TowerFallTeaser.jpg",
        gameUrl: "https://play.famobi.com/tower-fall",
        featured: false,
        popular: false
    },
    {
        id: "emoji-fun",
        name: "Emoji Fun",
        description: "Match emojis in this colorful and entertaining puzzle game. Create chains of matching emojis to score points and clear the board.",
        shortDescription: "Match emojis in this colorful puzzle game!",
        category: "puzzle",
        controls: "Mouse/Touch to swap",
        rating: 4.1,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/EmojiFunTeaser.jpg",
        gameUrl: "https://play.famobi.com/emoji-fun",
        featured: false,
        popular: false
    },
    {
        id: "bottle-flip",
        name: "Bottle Flip",
        description: "Test your timing skills in this addictive bottle flipping game. Flip bottles onto platforms of varying difficulty and become the ultimate bottle flip master!",
        shortDescription: "Master the art of bottle flipping!",
        category: "skill",
        controls: "Tap/Click to flip",
        rating: 4.7,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BottleFlipTeaser.jpg",
        gameUrl: "https://play.famobi.com/bottle-flip",
        featured: false,
        popular: true
    },
    {
        id: "slime-road",
        name: "Slime Road",
        description: "Guide your slime along a challenging road, avoiding obstacles and collecting coins. Grow your slime and see how far you can go in this endless runner.",
        shortDescription: "Guide your slime along a dangerous road!",
        category: "action",
        controls: "Tap/Click to move",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SlimeRoadTeaser.jpg",
        gameUrl: "https://play.famobi.com/slime-road",
        featured: false,
        popular: false
    },
    {
        id: "pipe-puzzle",
        name: "Pipe Puzzle",
        description: "Connect pipes to create a path for water to flow. Solve increasingly challenging puzzles using logic and planning in this classic puzzle game.",
        shortDescription: "Connect pipes to create a water flow path!",
        category: "puzzle",
        controls: "Mouse/Touch to rotate",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/PipePuzzleTeaser.jpg",
        gameUrl: "https://play.famobi.com/pipe-puzzle",
        featured: false,
        popular: false
    },
    {
        id: "funny-fred",
        name: "Funny Fred",
        description: "Help Fred collect stars and overcome obstacles in this charming platformer. Jump and slide your way through colorful levels in this entertaining adventure.",
        shortDescription: "Guide Fred through exciting platformer levels!",
        category: "adventure",
        controls: "Arrow keys/Tap to move",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FunnyFredTeaser.jpg",
        gameUrl: "https://play.famobi.com/funny-fred",
        featured: false,
        popular: false
    },
    {
        id: "barbara-and-kent",
        name: "Barbara and Kent",
        description: "Help Barbara and Kent navigate through challenging levels, using their unique abilities to overcome obstacles and puzzles in this cooperative adventure.",
        shortDescription: "Control two characters with unique abilities!",
        category: "adventure",
        controls: "Arrow keys/WASD to move",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/BarbaraAndKentTeaser.jpg",
        gameUrl: "https://play.famobi.com/barbara-and-kent",
        featured: false,
        popular: false
    },
    {
        id: "parking-panic",
        name: "Parking Panic",
        description: "Navigate through tight parking spaces and avoid collisions in this challenging parking simulation. Test your precision driving skills in increasingly difficult scenarios.",
        shortDescription: "Park cars in tight spaces without collisions!",
        category: "puzzle",
        controls: "Mouse/Touch to drag",
        rating: 4.2,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ParkingPanicTeaser.jpg",
        gameUrl: "https://play.famobi.com/parking-panic",
        featured: false,
        popular: false
    },
    {
        id: "super-thrower",
        name: "Super Thrower",
        description: "Test your throwing skills in this physics-based game. Aim carefully and throw objects to hit targets and solve puzzles across various challenging levels.",
        shortDescription: "Aim and throw objects to hit targets!",
        category: "skill",
        controls: "Mouse/Touch to aim and throw",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SuperThrowerTeaser.jpg",
        gameUrl: "https://play.famobi.com/super-thrower",
        featured: false,
        popular: false
    },
    {
        id: "food-rush",
        name: "Food Rush",
        description: "Serve customers quickly in this fast-paced restaurant game. Prepare and deliver orders on time to keep customers happy and earn tips in this time management challenge.",
        shortDescription: "Serve food quickly in this time management game!",
        category: "skill",
        controls: "Mouse/Touch to interact",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/FoodRushTeaser.jpg",
        gameUrl: "https://play.famobi.com/food-rush",
        featured: false,
        popular: false
    },
    {
        id: "parking-rush",
        name: "Parking Rush",
        description: "Navigate through busy parking lots and find a spot before time runs out. Avoid collisions and park precisely in this challenging driving simulation.",
        shortDescription: "Find a parking spot before time runs out!",
        category: "skill",
        controls: "Arrow keys/Swipe to drive",
        rating: 4.1,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ParkingRushTeaser.jpg",
        gameUrl: "https://play.famobi.com/parking-rush",
        featured: false,
        popular: false
    },
    {
        id: "giant-attack",
        name: "Giant Attack",
        description: "Defend your city from attacking giants in this action-packed tower defense game. Build defenses and upgrade weapons to repel increasingly powerful waves of giants.",
        shortDescription: "Defend your city from attacking giants!",
        category: "action",
        controls: "Mouse/Touch to place defenses",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GiantAttackTeaser.jpg",
        gameUrl: "https://play.famobi.com/giant-attack",
        featured: false,
        popular: false
    },
    {
        id: "gun-spin",
        name: "Gun Spin",
        description: "Test your reflexes in this wild west showdown game. Draw your gun faster than your opponent and become the quickest gunslinger in the west.",
        shortDescription: "Draw your gun faster than your opponent!",
        category: "action",
        controls: "Tap/Click to draw",
        rating: 4.7,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GunSpinTeaser.jpg",
        gameUrl: "https://play.famobi.com/gun-spin",
        featured: false,
        popular: true
    },
    {
        id: "good-shelves",
        name: "Good Shelves",
        description: "Organize items on shelves in this satisfying management game. Sort objects by type and optimize shelf space in increasingly challenging scenarios.",
        shortDescription: "Organize items neatly on shelves!",
        category: "puzzle",
        controls: "Mouse/Touch to drag",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/GoodShelvesTeaser.jpg",
        gameUrl: "https://play.famobi.com/good-shelves",
        featured: false,
        popular: false
    },
    {
        id: "dance-battle",
        name: "Dance Battle",
        description: "Show off your dance moves in this rhythm game. Match the beat and perform spectacular dance combinations to defeat your opponents and become the dance champion.",
        shortDescription: "Show off your dance moves in rhythm battles!",
        category: "skill",
        controls: "Arrow keys/Tap to dance",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/DanceBattleTeaser.jpg",
        gameUrl: "https://play.famobi.com/dance-battle",
        featured: false,
        popular: false
    },
    {
        id: "tile-journey",
        name: "Tile Journey",
        description: "Connect matching tiles to clear the board in this relaxing puzzle game. Plan your moves carefully to create paths and solve increasingly challenging levels.",
        shortDescription: "Connect tiles to create paths in this puzzle game!",
        category: "puzzle",
        controls: "Mouse/Touch to connect",
        rating: 4.2,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TileJourneyTeaser.jpg",
        gameUrl: "https://play.famobi.com/tile-journey",
        featured: false,
        popular: false
    },
    {
        id: "emoji-match",
        name: "Emoji Match",
        description: "Match identical emojis in this fun memory game. Flip cards to find pairs and test your memory skills with increasingly difficult layouts.",
        shortDescription: "Find matching emoji pairs in this memory game!",
        category: "puzzle",
        controls: "Mouse/Touch to flip",
        rating: 4.3,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/EmojiMatchTeaser.jpg",
        gameUrl: "https://play.famobi.com/emoji-match",
        featured: false,
        popular: false
    },
    {
        id: "tower-smash",
        name: "Tower Smash",
        description: "Smash through towers by launching projectiles strategically. Destroy targets and complete challenges in this physics-based destruction game.",
        shortDescription: "Smash towers with strategic projectile launches!",
        category: "action",
        controls: "Mouse/Touch to aim and launch",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TowerSmashTeaser.jpg",
        gameUrl: "https://play.famobi.com/tower-smash",
        featured: false,
        popular: false
    },
    {
        id: "save-the-princess",
        name: "Save the Princess",
        description: "Navigate through dangerous dungeons to rescue the princess. Solve puzzles, defeat enemies, and overcome obstacles in this exciting adventure game.",
        shortDescription: "Rescue the princess from dangerous dungeons!",
        category: "adventure",
        controls: "Arrow keys/Swipe to move",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SaveThePrincessTeaser.jpg",
        gameUrl: "https://play.famobi.com/save-the-princess",
        featured: false,
        popular: false
    },
    {
        id: "slope",
        name: "Slope",
        description: "Roll down an endless slope, avoiding obstacles and collecting points. Test your reflexes in this fast-paced, addictive endless runner.",
        shortDescription: "Roll down an endless slope and avoid obstacles!",
        category: "action",
        controls: "Arrow keys/Tilt to move",
        rating: 4.8,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/SlopeTeaser.jpg",
        gameUrl: "https://play.famobi.com/slope",
        featured: true,
        popular: true
    },
    {
        id: "color-tunnel",
        name: "Color Tunnel",
        description: "Navigate through a colorful 3D tunnel, matching your color to the upcoming segments. Test your reflexes and color recognition in this fast-paced arcade game.",
        shortDescription: "Race through a challenging color-matching tunnel!",
        category: "action",
        controls: "Mouse/Touch to switch colors",
        rating: 4.6,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/ColorTunnelTeaser.jpg",
        gameUrl: "https://play.famobi.com/color-tunnel",
        featured: false,
        popular: true
    },
    {
        id: "stair-race-3d",
        name: "Stair Race 3D",
        description: "Race up an endless staircase, collecting power-ups and avoiding obstacles. See how high you can climb in this challenging endless runner.",
        shortDescription: "Race up an endless staircase in this 3D runner!",
        category: "action",
        controls: "Swipe/Arrow keys to move",
        rating: 4.5,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/StairRace3dTeaser.jpg",
        gameUrl: "https://play.famobi.com/stair-race-3d",
        featured: false,
        popular: false
    },
    {
        id: "om-nom-run",
        name: "Om Nom Run",
        description: "Help Om Nom run through colorful levels, collecting candy and avoiding obstacles. Run, jump, and slide in this exciting endless runner featuring the cute character from Cut the Rope.",
        shortDescription: "Run and collect candy with the adorable Om Nom!",
        category: "action",
        controls: "Swipe/Arrow keys to move",
        rating: 4.7,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/OmNomRunTeaser.jpg",
        gameUrl: "https://play.famobi.com/om-nom-run",
        featured: true,
        popular: true
    },
    {
        id: "tnt-bomb",
        name: "TNT Bomb",
        description: "Place bombs strategically to destroy targets and clear levels. Use power-ups and plan carefully in this explosive puzzle game.",
        shortDescription: "Place bombs strategically to solve explosive puzzles!",
        category: "puzzle",
        controls: "Mouse/Touch to place bombs",
        rating: 4.4,
        imageUrl: "https://img.cdn.famobi.com/portal/html5games/images/tmp/TntBombTeaser.jpg",
        gameUrl: "https://play.famobi.com/tnt-bomb",
        featured: false,
        popular: false
    }
];

// Categories
const categories = [
    { id: "action", name: "Action" },
    { id: "adventure", name: "Adventure" },
    { id: "puzzle", name: "Puzzle" },
    { id: "skill", name: "Skill" }
]; 